#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Define the base path for the application, so that we can use it in the future (e.g. for deployment)
$BASE_PATH = __DIR__;

// Register the Composer autoloader...
require $BASE_PATH.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once $BASE_PATH.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
